# starship.toml
# 2026-01-18 jbgreer initial
#
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[container]
format = '[$symbol \[$name\]]($style) '

[character]
success_symbol = '[➜](bold green)'

[cmd_duration]
min_time = 500
format = 'underwent [$duration](bold yellow)'

[directory]
truncation_length = 255
truncate_to_repo = false
use_logical_path = false
