
set  -g default-terminal "screen-256color"
set  -g base-index      0
setw -g pane-base-index 0
# We need to set default-shell before calling new-session
set  -g default-shell "${pkgs}/bin/zsh"





set -g status-keys vi
set -g mode-keys   vi



# rebind main key: C-a
unbind C-b
set -g prefix C-a
bind -N "Send the prefix key through to the application" \
  C-a send-prefix




set  -g mouse             on
set  -g focus-events      off
setw -g aggressive-resize off
setw -g clock-mode-style  24
set  -s escape-time       500
set  -g history-limit     2000

# ============================================= #
# Load plugins with Home Manager                #
# --------------------------------------------- #

# tmuxplugin-catppuccin
# ---------------------
set -g @catppuccin_flavor 'mocha'

run-shell /nix/store/q7jqkcny6rspr3dq6q0q778lxviqi359-tmuxplugin-catppuccin-2c4cb5a/share/tmux-plugins/catppuccin/catppuccin.tmux


# tmuxplugin-vim-tmux-navigator
# ---------------------

run-shell /nix/store/527kcd4n08w85mhpf6yvsjxf23597lsr-tmuxplugin-vim-tmux-navigator-unstable-2022-08-21/share/tmux-plugins/vim-tmux-navigator/vim-tmux-navigator.tmux


# tmuxplugin-catppuccin
# ---------------------

run-shell /nix/store/y5xlx7n9kmffx0hcvmhwrm1hxc5pyi52-tmuxplugin-catppuccin-unstable-2024-05-15/share/tmux-plugins/catppuccin/catppuccin.tmux

# ============================================= #


      # tmux.nix extraConfig

      set -g status-position top  #

      # change vertical split key to |
      unbind %
      bind | split-window -h

      # change hortizontal split key to -
      unbind '"'
      bind - split-window -v

      # resize of panel
      bind -r j resize-pane -D 5
      bind -r k resize-pane -U 5
      bind -r l resize-pane -R 5
      bind -r h resize-pane -L 5

      bind -r m resize-pane -Z

      # start selecting text with v
      bind-key -T copy-mode-vi 'v' send -X begin-selection
      # copy text with y
      bind-key -T copy-mode-vi 'y' send -X copy-selection
      # don't exit copy mode when dragging with mouse
      unbind -T copy-mode-vi MouseDragEnd1Pane

      #set -g @catppuccin_flavour 'mocha'
      set -g @catppuccin_window_left_separator ""
      set -g @catppuccin_window_right_separator " "
      set -g @catppuccin_window_middle_separator " █"
      set -g @catppuccin_window_number_position "right"
      set -g @catppuccin_window_default_fill "number"
      set -g @catppuccin_window_default_text "#W"
      set -g @catppuccin_window_current_fill "number"
      set -g @catppuccin_window_current_text "#W"
      set -g @catppuccin_status_modules_right "directory user host session"
      set -g @catppuccin_status_left_separator  " "
      set -g @catppuccin_status_right_separator ""
      set -g @catppuccin_status_fill "icon"
      set -g @catppuccin_status_connect_separator "no"
      set -g @catppuccin_directory_text "#{pane_current_path}"
      # tmux.nix extraConfig
    