# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=,preferred,auto,auto
monitor=,highres,auto,1

windowrule = float, ^(thunar)$
windowrule = center, ^(thunar)$
windowrule = size 1080 900, ^(thunar)$

layerrule = blur, ^(wofi)$

input {
    kb_layout = us
    kb_options = caps:super
    follow_mouse = 1

    touchpad {
        natural_scroll = false
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

gestures {
    workspace_swipe = true
    workspace_swipe_fingers = 3
}

source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/theme.conf

misc {
    disable_hyprland_logo = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = false
}

